### ISSUE TITLE
Make an examples app.

### ISSUE THREAD

**Issue by Akim95** [Akim95/billplz-graphql#1]
Submit your example app for this project.

**Comment by mohitmanuja** [comment]
Hey, I am interested.  Tell me what things you want in app i.e First screen should contain etc.

**Comment by Akim95** [comment]
Firstly, Billplz is a Malaysia based payment gateway. You could make any super simple app like a donation page or e-commerce site like this [link](https://github.com/Akim95/billplz-graphql/tree/master/examples/billplz-shop).

Register here to get an API key: https://billplz-staging.herokuapp.com

Thanks!
