### ISSUE TITLE
Create Deploy to Heroku Button

### ISSUE THREAD

**Issue by Akim95** [Akim95/billplz-graphql#3]
Reference: https://devcenter.heroku.com/articles/heroku-button

**Comment by raavanan** [comment]
hey @Akim95 I want to give this a go. can you tell me where you want this deploy button.

**Comment by Akim95** [comment]
Hi @raavanan, wherever in README.

Thanks!

**Comment by KayvanMazaheri** [comment]
created a PR here #4
